Fix a broken compile of the packaged RRDs.pm module on Ubuntu Breezy Badger with gcc 4.0.2 and bump the module's version number.  Without this fix, the following error occurs:
    $ cc -c -I.. -I../src -I../gd1.3 -D_REENTRANT -D_GNU_SOURCE
    -DTHREADS_HAVE_PIDS -DDEBIAN -fno-strict-aliasing -pipe
    -I/usr/local/include -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64
    -DHAVE_CONFIG_H -O2 -DVERSION=\"1.000503\"
    -DXS_VERSION=\"1.000503\" -fPIC "-I/usr/lib/perl/5.8/CORE"
    -DPERLPATCHLEVEL=8 RRDs.c
    In file included from ../src/rrd_tool.h:25,
                     from RRDs.xs:13:
    ../src/config_aux.h:8:1: warning: "strchr" redefined
    In file included from /usr/include/string.h:417,
                     from /usr/lib/perl/5.8/CORE/perl.h:731,
                     from RRDs.xs:6:
    /usr/include/bits/string2.h:396:1: warning: this is the location
    of the previous definition
    In file included from ../src/rrd_tool.h:25,
                     from RRDs.xs:13:
    ../src/config_aux.h:80:2: error: #error "Can't compile without
    finite function"
    ../src/config_aux.h:84:2: error: #error "Can't compile without
    isinf function"

* configure.in:
  Bump RRDs' required version number to 1.000503.

* packages/rrdtool-1.0.50/perl-shared/RRDs.pm:
  Bump the RRDs module's version number to 1.000503.

* packages/rrdtool-1.0.50/perl-shared/RRDs.xs:
  Fix the compilation problem by explicitly including rrdtool's
    config.h using a relative path.